In [20]:
import torch
import numpy as np

x, y = torch.randn(2, 2), torch.randn(2, 2)

print(x + y)

x.view(4)
x.numpy()

tensor([[-0.6293, -0.4417],
        [ 0.5120,  0.4998]])


array([[-0.7462041 ,  0.4422612 ],
       [-0.10883775,  0.10878663]], dtype=float32)

In [22]:
if torch.cuda.is_available():
    device = torch.device('cuda')
    print('CUDA Avaiable')
    
    torch.ones(5, device=device)

CUDA Avaiable


In [48]:
# Градиенты
x = torch.randn(3, requires_grad=True)
print(x)

y = x + 2
print(y)

z = y * y * 2
z = z.mean()
print(z)

z.backward() # dz/dx

v = x.detach()




tensor([ 0.1589, -1.1078,  0.2239], requires_grad=True)
tensor([2.1589, 0.8922, 2.2239], grad_fn=<AddBackward0>)
tensor(6.9349, grad_fn=<MeanBackward0>)


In [60]:
weights = torch.ones(4, requires_grad=True)

# for epoch in range(3):
#     model_output = (weights * 3).sum()
#     model_output.backward()
#     print(weights.grad)
#     weights.grad.zero_()
    
weights.grad.zero_()
    
optim = torch.optim.SGD(weights, lr=0.01)
optim.step()

AttributeError: 'NoneType' object has no attribute 'zero_'

In [3]:
import torch

x = torch.tensor(1.0)
y = torch.tensor(2.0)
w = torch.tensor(1.0, requires_grad=True)

y_hat = w * x
loss = (y_hat - y) ** 2

print(loss)

loss.backward()
print(w.grad)





tensor(1., grad_fn=<PowBackward0>)
tensor(-2.)
