In [3]:
import torch

print(torch.empty(2, 2))
print(torch.zeros(2, 2))
print(torch.randn(2, 2))

tensor([[2.7080e+25, 3.0693e-41],
        [2.6590e+25, 3.0693e-41]])
tensor([[0., 0.],
        [0., 0.]])
tensor([[0.2241, 1.0072],
        [1.2123, 0.6596]])
