In [2]:
import torch
import numpy as np

x, y = torch.randn(2, 2), torch.randn(2, 2)

print(x + y)

x.view(4)
x.numpy()

tensor([[-0.3762, -0.8840],
        [-0.2934, -0.7305]])


array([[ 0.07065374, -0.6165316 ],
       [-0.5756845 , -0.821687  ]], dtype=float32)

In [3]:
if torch.cuda.is_available():
    device = torch.device('cuda')
    print('CUDA Avaiable')
    
    torch.ones(5, device=device)

CUDA Avaiable


In [4]:
# Градиенты
x = torch.randn(3, requires_grad=True)
print(x)

y = x + 2
print(y)

z = y * y * 2
z = z.mean()
print(z)

z.backward() # dz/dx

v = x.detach()




tensor([-0.6679,  1.7979, -0.5851], requires_grad=True)
tensor([1.3321, 3.7979, 1.4149], grad_fn=<AddBackward0>)
tensor(12.1336, grad_fn=<MeanBackward0>)


In [5]:
weights = torch.ones(4, requires_grad=True)

# for epoch in range(3):
#     model_output = (weights * 3).sum()
#     model_output.backward()
#     print(weights.grad)
#     weights.grad.zero_()
    
weights.grad.zero_()
    
optim = torch.optim.SGD(weights, lr=0.01)
optim.step()

AttributeError: 'NoneType' object has no attribute 'zero_'

In [6]:
import torch

x = torch.tensor(1.0)
y = torch.tensor(2.0)
w = torch.tensor(1.0, requires_grad=True)

y_hat = w * x
loss = (y_hat - y) ** 2

print(loss)

loss.backward()
print(w.grad)


tensor(1., grad_fn=<PowBackward0>)
tensor(-2.)


In [23]:
x = torch.randn(3, requires_grad=True)
print(x)

y = x + 2
print(y) # with fradient func

z = (y * y * 2).mean()
print(z)

z.backward() # dz/dx
print(x.grad)



tensor([1.6350, 0.1924, 0.3266], requires_grad=True)
tensor([3.6350, 2.1924, 2.3266], grad_fn=<AddBackward0>)
tensor(15.6218, grad_fn=<MeanBackward0>)
tensor([4.8467, 2.9232, 3.1021])
